import type { Metadata } from "next";

import "./globals.css";
import "../css/bootstrap.css";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "DS",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="page-container">
        <Navbar />
          <main className="content-wrapper">{children}</main>
        </div>
      </body>
    </html>
  );
}
